services:
  foot-api:
    image: foot-api:${VERSION}
    container_name: foot-api
    ports:
      - "3000:3000"
    environment:
      VERSION: "${VERSION}"
    restart: unless-stopped
    mem_limit: 256m

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=24h"
    restart: unless-stopped
    depends_on:
      - foot-api
    mem_limit: 256m

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    mem_limit: 256m

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=142.93.156.69
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://142.93.156.69:5678/
      - N8N_SECURE_COOKIE=false
      - TZ=America/Toronto
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped


volumes:
  prometheus_data:
  grafana_data:
  n8n_data: