services:
  foot-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    # Optionnel: limite CPU pour faciliter une démo de saturation
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - foot-api

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
